//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobBoard.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SavedJob
    {
        public int SavedJobID { get; set; }
        public string Title { get; set; }
        public string UserID { get; set; }
        public Nullable<int> PositionID { get; set; }
    
        public virtual Position Position { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
